baseURL = 'https://umbrella-plus.com.ua/'
title = 'Umbrella Plus'
relativeURLs = true
enableRobotsTXT = true
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = false

[languages]
    [languages.ru]
        contentDir = 'content/ru-lang'
        languageCode = 'ru-UA'
        languageName = 'RU'
        weight = 10
            [[languages.ru.menus.main]]
                name = 'Услуги'
                pageRef = '/services'
                weight = 10
                identifier = 'services'
                    [[languages.ru.menus.main]]
                        name = 'Лечение алкоголизма'
                        pageRef = '/services'
                        weight = 10
                        parent = 'services'
                    [[languages.ru.menus.main]]
                        name = 'Лечение наркомании'
                        pageRef = '/services-nark'
                        weight = 20
                        parent = 'services'
            [[languages.ru.menus.main]]
                name = 'Врачи'
                url = '/#doctors'
                weight = 20
                identifier = 'doctors'
            [[languages.ru.menus.main]]
                name = 'Блог'
                pageRef = '/blog'
                weight = 30
            [[languages.ru.menus.main]]
                name = 'Филиалы'
                weight = 40
                pageRef = '#'
                identifier = 'filials'
                    [[languages.ru.menus.main]]
                        name = 'Одесса'
                        pageRef = '/lechenie-alc'
                        weight = 10
                        parent = 'filials'
                    [[languages.ru.menus.main]]
                        name = 'Киев'
                        pageRef = '/kiev'
                        weight = 20
                        parent = 'filials'
                    [[languages.ru.menus.main]]
                        name = 'Харьков'
                        pageRef = '/kharkiv'
                        weight = 30
                        parent = 'filials'
                    [[languages.ru.menus.main]]
                        name = 'Львов'
                        pageRef = '/lviv'
                        weight = 40
                        parent = 'filials'
                    [[languages.ru.menus.main]]
                        name = 'Днепр'
                        pageRef = '/dnepr'
                        weight = 50
                        parent = 'filials'
                    [[languages.ru.menus.main]]
                        name = 'Запорожье'
                        pageRef = '/zaporozie'
                        weight = 60
                        parent = 'filials'
                    [[languages.ru.menus.main]]
                        name = 'Черноморск'
                        pageRef = '/chornomorsk'
                        weight = 70
                        parent = 'filials'
                    [[languages.ru.menus.main]]
                        name = 'Каменское'
                        pageRef = '/kamianske'
                        weight = 80
                        parent = 'filials'
            [[languages.ru.menus.main]]
                name = 'Отзывы'
                url = '/#image-carousel'
                weight = 50
            [[languages.ru.menus.main]]
                name = 'Дополнительно'
                weight = 60
                identifier = 'extra'
                    [[languages.ru.menus.main]]
                        name = 'Контакты'
                        pageRef = '/contacts'
                        weight = 10
                        parent = 'extra'
                    [[languages.ru.menus.main]]
                        name = 'О нас'
                        pageRef = '/about'
                        weight = 20
                        parent = 'extra'
    [languages.uk]
        contentDir = 'content/ua-lang'
        languageCode = 'uk-UA'
        languageName = 'UA'
        weight = 20
            [[languages.uk.menus.main]]
                name = 'Послуги'
                pageRef = '/services'
                weight = 10
            identifier = 'services'
                    [[languages.uk.menus.main]]
                        name = 'Лікування алкоголізму'
                        pageRef = '/services'
                        weight = 10
                        parent = 'services'
                    [[languages.uk.menus.main]]
                        name = 'Лікування наркоманії'
                        pageRef = '/services-nark'
                        weight = 20
                        parent = 'services'
            [[languages.uk.menus.main]]
                name = 'Лікарі'
                url = '/#doctors'
                weight = 20
                identifier = 'doctors'
            [[languages.uk.menus.main]]
                name = 'Блог'
                pageRef = '/blog'
                weight = 30
            [[languages.uk.menus.main]]
            name = 'Філіали'
            weight = 30
            identifier = 'filials'
                    [[languages.uk.menus.main]]
                        name = 'Одеса'
                        pageRef = '/lechenie-alc'
                        weight = 10
                        parent = 'filials'
                    [[languages.uk.menus.main]]
                        name = 'Київ'
                        pageRef = '/kiev'
                        weight = 20
                        parent = 'filials'
                    [[languages.uk.menus.main]]
                        name = 'Харьків'
                        pageRef = '/kharkiv'
                        weight = 30
                        parent = 'filials'
                    [[languages.uk.menus.main]]
                        name = 'Львів'
                        pageRef = '/lviv'
                        weight = 40
                        parent = 'filials'
                    [[languages.uk.menus.main]]
                        name = 'Дніпро'
                        pageRef = '/dnepr'
                        weight = 50
                        parent = 'filials'
                    [[languages.uk.menus.main]]
                        name = 'Запоріжжя'
                        pageRef = '/zaporozie'
                        weight = 60
                        parent = 'filials'
                    [[languages.uk.menus.main]]
                        name = 'Чорноморськ'
                        pageRef = '/chornomorsk'
                        weight = 70
                        parent = 'filials'
                    [[languages.uk.menus.main]]
                        name = 'Кам’янське'
                        pageRef = '/kamianske'
                        weight = 80
                        parent = 'filials'
            [[languages.uk.menus.main]]
                name = 'Відгуки'
                url = '/#image-carousel'
                weight = 50
            [[languages.uk.menus.main]]
                name = 'Додатково'
                weight = 60
                identifier = 'extra'
                    [[languages.uk.menus.main]]
                        name = 'Контакти'
                        pageRef = '/contacts'
                        weight = 10
                        parent = 'extra'
                    [[languages.uk.menus.main]]
                        name = 'Про нас'
                        pageRef = '/about'
                        weight = 20
                        parent = 'extra'